site_name: JHANSI's Work Documentation
site_description: you can find all my documented work here.
site_url: https://sitename.example


theme:
  name: material
  custom_dir: overrides

  font:
    text: Inter # all google fonts are 
    code: Red Hat Mono

  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.follow

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange


plugins:
  - search
  - blog:
      blog_dir: .
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "posts/.*" 
      pretty_print: true 
      date_from_meta: 
        as_creation: date.created 
        as_update: date.updated


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: simple/gmail
      link: mailto:623182@student.nitandhra.ac.in

hooks:
  - hooks/socialmedia.py