authors:
  jhansi:
    name: JHANSI REDDY TANGIRALA
    description: creator
    email: 623182@student.nitandhra.ac.in
    avatar: assets/jhansi_author.png
    url: https://github.com/JHANSI-REDDY-TANGIRALA
  Anish:
    name: Anish
    description: co-author
    avatar: assets/koala.png
  